
import React, { useState, useEffect, useCallback, useRef } from 'react';
import JSZip from 'jszip';
import { 
  Project,
  Platform,
  FileNode, 
  Message, 
  AIStatus 
} from './types';
import { 
  IconFolder, 
  IconFile, 
  IconBot, 
  IconTerminal, 
  IconCpu, 
  IconSave, 
  IconShare,
  IconSettings,
  IconBug,
  IconClipboard,
  IconPlus,
  IconUpload,
  IconLink
} from './components/Icons';
import { generateAppStructure, getSuggestions, fixCode, optimizeAndCorrectCode } from './services/geminiService';
import LivePreview from './components/LivePreview';
import AIConfigModal from './components/AIConfigModal';

const EXPORT_CATEGORIES = [
  { name: 'Linux Architect', options: ['OCI-Images (Docker/Podman)', 'Flatpak', 'Snap', 'AppImage', 'deb / rpm (Nativos)'] },
  { name: 'Windows Studio', options: ['MSIX', 'MSI', 'EXE (Tradicional)'] },
  { name: 'Mobile Forge', options: ['AAB (Android App Bundle)', 'APK (Sideloading)', 'IPA (iOS/iPadOS)'] },
  { name: 'Web & Cloud Sync', options: ['Wasm (WebAssembly)', 'Wasm Components', 'PWA (Manifests)'] },
  { name: 'Infraestrutura (IaC)', options: ['Terraform/OpenTofu Plans', 'Helm Charts (Kubernetes)'] }
];

const SIMULATED_ERRORS = [
    "Cross-Site Scripting (XSS) Vulnerability",
    "Null Pointer Exception in core logic",
    "Infinite Loop leading to performance degradation",
    "API Rate Limit Exceeded due to inefficient calls",
    "Insecure Direct Object Reference (IDOR)",
    "Memory Leak in data processing function",
    "Network Timeout on critical resource fetch",
];

const INITIAL_PROJECT: Project = {
  id: 'proj-' + Date.now(),
  name: 'New Project',
  description: 'AI-generated application structure',
  structure: [
    { id: '1', name: 'src', type: 'folder', isOpen: true, children: [
      { id: '2', name: 'App.tsx', type: 'file', content: 'export default function App() {\n  return (\n    <div className="p-8 bg-zinc-900 min-h-screen text-white flex flex-col items-center justify-center">\n      <h1 className="text-4xl font-bold mb-4 text-indigo-400">Welcome to ZERO</h1>\n      <p className="text-zinc-400">Your universal app architect is ready.</p>\n      <button className="mt-6 px-6 py-2 bg-indigo-600 rounded-full hover:bg-indigo-700 transition">Get Started</button>\n    </div>\n  );\n}', language: 'typescript' }
    ]},
    { id: '3', name: 'README.md', type: 'file', content: '# My Project\nGenerated by ZERO', language: 'markdown' }
  ],
  lastSaved: Date.now(),
  config: {
    targetPlatform: Platform.WEB,
    language: 'TypeScript',
    localAIEngine: {
      status: 'idle',
      downloadProgress: 0
    },
    localAIProviders: [],
    cloudAIProviders: [
      { id: 'cloud-default-gemini', name: 'Default Gemini', provider: 'Gemini', model: 'gemini-3-pro-preview', apiKey: '' }
    ],
    activeAIProviderId: 'cloud-default-gemini'
  }
};

// Helper to build a proper file tree from a flat path list
const buildFileTree = (files: { path: string; content: string; language: string }[]): FileNode[] => {
  const fileTree: FileNode[] = [];

  const getFileLanguage = (fileName: string): string => {
    const extension = fileName.split('.').pop()?.toLowerCase();
    switch (extension) {
      case 'ts':
      case 'tsx':
        return 'typescript';
      case 'js':
      case 'jsx':
        return 'javascript';
      case 'json':
        return 'json';
      case 'md':
        return 'markdown';
      case 'css':
        return 'css';
      case 'html':
        return 'html';
      case 'py':
        return 'python';
      case 'cs':
        return 'csharp';
      case 'java':
        return 'java';
      default:
        return 'plaintext';
    }
  };


  files.forEach((file) => {
    // Normalize path and remove the root folder part
    const pathParts = file.path.replace(/\\/g, '/').split('/').filter(p => p);
    if (pathParts.length > 1) {
        pathParts.shift();
    }
    
    let currentLevel = fileTree;

    pathParts.forEach((part, partIndex) => {
      if (partIndex === pathParts.length - 1) {
        // It's a file
        currentLevel.push({
          id: `file-${file.path}-${Date.now()}`,
          name: part,
          type: 'file',
          content: file.content,
          language: getFileLanguage(part),
        });
      } else {
        // It's a folder
        let existingFolder = currentLevel.find(node => node.name === part && node.type === 'folder');

        if (existingFolder) {
          currentLevel = existingFolder.children!;
        } else {
          const newFolder: FileNode = {
            id: `folder-${file.path.substring(0, file.path.indexOf(part) + part.length)}-${Date.now()}`,
            name: part,
            type: 'folder',
            children: [],
            isOpen: true,
          };
          currentLevel.push(newFolder);
          currentLevel = newFolder.children!;
        }
      }
    });
  });

  return fileTree;
};


const App: React.FC = () => {
  const [project, setProject] = useState<Project>(INITIAL_PROJECT);
  const [activeFileId, setActiveFileId] = useState<string | null>('2');
  const [messages, setMessages] = useState<Message[]>([]);
  const [userInput, setUserInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [showExportModal, setShowExportModal] = useState(false);
  const [selectedFormat, setSelectedFormat] = useState<string>('');
  const [isExporting, setIsExporting] = useState(false);
  const [showAIConfigModal, setShowAIConfigModal] = useState(false);
  const [viewMode, setViewMode] = useState<'code' | 'preview' | 'split'>('split');
  const [isAutoSaving, setIsAutoSaving] = useState(false);
  const [isFixingCode, setIsFixingCode] = useState(false);
  const [isCopying, setIsCopying] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const uploadFolderRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const timer = setInterval(() => {
      setIsAutoSaving(true);
      localStorage.setItem('zero_project', JSON.stringify(project));
      setTimeout(() => setIsAutoSaving(false), 1000);
    }, 15000);
    return () => clearInterval(timer);
  }, [project]);

  useEffect(() => {
    const saved = localStorage.getItem('zero_project');
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        if (parsed.config.cloudAI) {
            parsed.config.cloudAIProviders = [{ id: 'cloud-default-gemini', name: 'Default Gemini', provider: 'Gemini', model: parsed.config.cloudAI.model, apiKey: parsed.config.cloudAI.apiKey || '' }];
            delete parsed.config.cloudAI;
        }
        if (parsed.config.localAI) {
            parsed.config.localAIProviders = [];
            parsed.config.localAIEngine = { status: parsed.config.localAI.engineStatus || 'idle' };
            delete parsed.config.localAI;
        }
        if (!parsed.config.activeAIProviderId) {
            parsed.config.activeAIProviderId = 'cloud-default-gemini';
        }
        setProject(parsed);
      } catch (e) {
        console.error("Failed to load saved project", e);
        setProject(INITIAL_PROJECT);
      }
    }
  }, []);

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const getActiveProvider = () => {
    const { activeAIProviderId, cloudAIProviders, localAIProviders } = project.config;
    return [...cloudAIProviders, ...localAIProviders].find(p => p.id === activeAIProviderId);
  };

  const handleNewProject = () => {
    const newProject = { 
      ...JSON.parse(JSON.stringify(INITIAL_PROJECT)),
      id: 'proj-' + Date.now(), 
      lastSaved: Date.now() 
    };
    setProject(newProject);
    setActiveFileId(null);
    localStorage.removeItem('zero_project');
    setMessages([{ id: Date.now().toString(), role: 'system', text: 'Novo projeto iniciado. Descreva o que você quer construir.', timestamp: Date.now() }]);
  };

  const handleSendMessage = async () => {
    if (!userInput.trim()) return;
    const activeProvider = getActiveProvider();
    if (!activeProvider) {
      setMessages(prev => [...prev, { id: Date.now().toString(), role: 'system', text: 'Nenhum provedor de IA ativo selecionado.', timestamp: Date.now() }]);
      return;
    }
    setMessages(prev => [...prev, { id: Date.now().toString(), role: 'user', text: userInput, timestamp: Date.now() }]);
    setUserInput('');
    setIsGenerating(true);

    const isWindowsPlatform = project.config.targetPlatform === Platform.WINDOWS;
    const initialSystemMessage = isWindowsPlatform
      ? 'Entendido. Elaborando a arquitetura para um aplicativo nativo do Windows usando WinUI 3...'
      : `Iniciando a geração para a plataforma: ${project.config.targetPlatform}...`;
      
    setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: 'system', text: initialSystemMessage, timestamp: Date.now() }]);

    try {
        const result = await generateAppStructure(userInput, project.config.targetPlatform, project);
        if (!result.files || result.files.length === 0) {
            throw new Error("A IA não retornou nenhum arquivo.");
        }
        const finalStructure = buildFileTree(result.files);

        setProject(prev => ({...prev, name: result.name || prev.name, structure: finalStructure}));
        setMessages(prev => [...prev, { id: (Date.now() + 2).toString(), role: 'assistant', text: `Estrutura do projeto "${result.name}" gerada com sucesso utilizando ${activeProvider.name}.`, timestamp: Date.now() }]);
        
        const findFirstFile = (nodes: FileNode[]): FileNode | null => {
          for (const node of nodes) {
            if (node.type === 'file') return node;
            if (node.children) {
              const first = findFirstFile(node.children);
              if (first) return first;
            }
          }
          return null;
        };
        const firstFile = findFirstFile(finalStructure);
        if (firstFile) {
            setActiveFileId(firstFile.id);
        }

        setViewMode('split');
    } catch (error: any) {
      console.error(error);
      const errorMessage = error.message || `Erro na requisição para ${activeProvider.name}. Verifique a chave de API e a configuração do modelo.`;
      setMessages(prev => [...prev, { id: Date.now().toString(), role: 'system', text: errorMessage, timestamp: Date.now() }]);
    } finally {
      setIsGenerating(false);
    }
  };
  
  const handleExportProject = async () => {
    if (isExporting) return;
    setIsExporting(true);
  
    const zip = new JSZip();
  
    const addFilesToZip = (nodes: FileNode[], currentPath: string) => {
      nodes.forEach(node => {
        const newPath = currentPath ? `${currentPath}/${node.name}` : node.name;
        if (node.type === 'folder') {
          addFilesToZip(node.children || [], newPath);
        } else if (node.type === 'file') {
          zip.file(newPath, node.content || '');
        }
      });
    };
  
    addFilesToZip(project.structure, '');
  
    try {
      const content = await zip.generateAsync({ type: 'blob' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(content);
      link.download = `${project.name.replace(/\s+/g, '_')}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
    } catch (err) {
      console.error("Failed to export project:", err);
      alert("Houve um erro ao exportar o projeto.");
    } finally {
      setIsExporting(false);
      setShowExportModal(false);
      setSelectedFormat('');
    }
  };

  const handleSimulateAndFix = async () => {
    if (!activeFile || isFixingCode) return;

    setIsFixingCode(true);
    const randomError = SIMULATED_ERRORS[Math.floor(Math.random() * SIMULATED_ERRORS.length)];

    setMessages(prev => [...prev, { id: Date.now().toString(), role: 'system', text: `Simulando erro: "${randomError}" em ${activeFile.name}...`, timestamp: Date.now() }]);
    
    try {
      const fixedCode = await fixCode(activeFile.content || '', randomError, project);
      setProject(prev => ({ ...prev, structure: updateFileContent(prev.structure, activeFile.id, fixedCode) }));
      setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: 'assistant', text: `Problema detectado e corrigido com sucesso em ${activeFile.name}.`, timestamp: Date.now() }]);
    } catch (error) {
      console.error("Error fixing code:", error);
      setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: 'system', text: `Falha ao corrigir o código.`, timestamp: Date.now() }]);
    } finally {
      setIsFixingCode(false);
    }
  };

  const handleCopyAllCode = async () => {
    if (isCopying) return;
    setIsCopying(true);
    setMessages(prev => [...prev, { id: Date.now().toString(), role: 'system', text: 'Analisando e otimizando todo o código do projeto...', timestamp: Date.now() }]);

    const flattenProjectCode = (nodes: FileNode[]): string => {
        let allCode = '';
        const traverse = (nodes: FileNode[], path: string) => {
            for (const node of nodes) {
                const currentPath = path ? `${path}/${node.name}` : node.name;
                if (node.type === 'file' && node.content) {
                    allCode += `// Path: ${currentPath}\n\n${node.content}\n\n---\n\n`;
                }
                if (node.children) {
                    traverse(node.children, currentPath);
                }
            }
        };
        traverse(nodes, '');
        return allCode;
    };

    const fullCode = flattenProjectCode(project.structure);

    try {
        const optimizedCode = await optimizeAndCorrectCode(fullCode, project);
        await navigator.clipboard.writeText(optimizedCode);
        setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: 'assistant', text: 'Código otimizado e copiado para a área de transferência!', timestamp: Date.now() }]);
    } catch (error) {
        console.error("Error optimizing code:", error);
        setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: 'system', text: 'Falha ao otimizar o código.', timestamp: Date.now() }]);
    } finally {
        setIsCopying(false);
    }
  };

  const handleUploadClick = () => {
    uploadFolderRef.current?.click();
  };

  const handleFolderUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (!files || files.length === 0) return;

    const readFileAsText = (file: File): Promise<string> => {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsText(file);
        });
    };

    try {
        const fileContents = await Promise.all(
            Array.from(files).map(async (file: File) => ({
                path: (file as any).webkitRelativePath,
                content: await readFileAsText(file),
                language: '' 
            }))
        );

        if (fileContents.length > 0) {
            const newStructure = buildFileTree(fileContents);
            const rootFolderName = fileContents[0].path.split('/')[0];
            
            setProject(prev => ({
                ...prev,
                id: 'proj-' + Date.now(),
                name: rootFolderName || 'Uploaded Project',
                structure: newStructure,
                lastSaved: Date.now()
            }));

            setActiveFileId(null);
            setMessages([{ id: Date.now().toString(), role: 'system', text: 'Projeto carregado com sucesso. Pronto para analisar.', timestamp: Date.now() }]);
        }
    } catch (error) {
        console.error("Error reading folder:", error);
        setMessages(prev => [...prev, { id: Date.now().toString(), role: 'system', text: 'Erro ao carregar a pasta.', timestamp: Date.now() }]);
    }

    // Reset the input value to allow uploading the same folder again
    event.target.value = '';
  };

  const handleImportFromLink = () => {
    const url = prompt("Cole o URL do repositório (ex: GitHub):");
    if (url) {
      setMessages(prev => [...prev, { id: Date.now().toString(), role: 'system', text: `A importação de ${url} é um recurso futuro. Por enquanto, use o upload de pasta.`, timestamp: Date.now() }]);
    }
  };


  const findFile = (nodes: FileNode[], id: string): FileNode | null => {
    for (const node of nodes) {
      if (node.id === id) return node;
      if (node.children) { const found = findFile(node.children, id); if (found) return found; }
    }
    return null;
  };

  const updateFileContent = (nodes: FileNode[], id: string, content: string): FileNode[] => (
    nodes.map(node => (node.id === id ? { ...node, content } : node.children ? { ...node, children: updateFileContent(node.children, id, content) } : node))
  );

  const handleToggleFolder = (folderId: string) => {
    const toggleRecursively = (nodes: FileNode[]): FileNode[] => {
      return nodes.map(node => {
        if (node.id === folderId && node.type === 'folder') {
          return { ...node, isOpen: !node.isOpen };
        }
        if (node.children) {
          return { ...node, children: toggleRecursively(node.children) };
        }
        return node;
      });
    };

    setProject(currentProject => ({
      ...currentProject,
      structure: toggleRecursively(currentProject.structure),
    }));
  };

  const activeFile = activeFileId ? findFile(project.structure, activeFileId) : null;

  return (
    <div className="flex flex-col h-screen overflow-hidden text-zinc-300 font-sans">
      <header className="h-14 border-b border-zinc-800 bg-zinc-950 flex items-center justify-between px-4 shrink-0 z-10">
        <div className="flex items-center gap-4">
          <div className="bg-indigo-600 p-1.5 rounded-lg"><span className="font-bold text-white text-xl tracking-tighter">ZERO</span></div>
          <div className="h-6 w-[1px] bg-zinc-800 mx-2" />
          <h1 className="font-medium text-zinc-100">{project.name}</h1>
        </div>
        <div className="absolute left-1/2 -translate-x-1/2 bg-zinc-900 border border-zinc-800 rounded-lg p-1 flex items-center gap-1">
          <button onClick={() => setViewMode('code')} className={`px-3 py-1 rounded-md text-xs font-medium transition ${viewMode === 'code' ? 'bg-zinc-800 text-white' : 'text-zinc-500 hover:text-zinc-300'}`}>Código</button>
          <button onClick={() => setViewMode('split')} className={`px-3 py-1 rounded-md text-xs font-medium transition ${viewMode === 'split' ? 'bg-zinc-800 text-white' : 'text-zinc-500 hover:text-zinc-300'}`}>Dividido</button>
          <button onClick={() => setViewMode('preview')} className={`px-3 py-1 rounded-md text-xs font-medium transition ${viewMode === 'preview' ? 'bg-zinc-800 text-white' : 'text-zinc-500 hover:text-zinc-300'}`}>Visualização</button>
        </div>
        <div className="flex items-center gap-3">
          {isAutoSaving && <span className="text-[10px] text-zinc-500 animate-pulse uppercase tracking-widest">Auto-salvando...</span>}
          <div className="flex items-center gap-2 bg-zinc-900 rounded-xl p-1 pr-2 border border-zinc-800">
             <div className="px-2 py-1 rounded-lg text-xs flex items-center gap-2 bg-zinc-800">
                { getActiveProvider()?.hasOwnProperty('apiKey') ? <IconBot /> : <IconCpu /> }
                <span className="font-medium text-zinc-300 truncate max-w-24">{getActiveProvider()?.name || 'N/A'}</span>
             </div>
             <button onClick={() => setShowAIConfigModal(true)} className="p-1.5 hover:bg-zinc-800 rounded-lg text-zinc-500 hover:text-indigo-400 transition" title="Configurações de IA"><IconSettings size={14} /></button>
          </div>
          <button onClick={() => alert('Projeto Salvo!')} className="p-2 hover:bg-zinc-900 rounded-lg transition" title="Salvar Projeto"><IconSave /></button>
          <button onClick={() => setShowExportModal(true)} className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-1.5 rounded-lg font-medium transition shadow-lg shadow-indigo-500/10"><IconShare /> Exportar</button>
        </div>
      </header>

      <main className="flex flex-1 overflow-hidden">
        <aside className="w-64 border-r border-zinc-800 bg-zinc-950/50 flex flex-col overflow-y-auto shrink-0">
          <div className="p-4 border-b border-zinc-800 flex justify-between items-center">
            <h2 className="text-xs font-bold uppercase tracking-wider text-zinc-500">Explorer</h2>
            <div className="flex items-center gap-2">
                <input type="file" ref={uploadFolderRef} onChange={handleFolderUpload} className="hidden" webkitdirectory="" directory="" multiple />
                <button onClick={handleUploadClick} title="Carregar Projeto" className="text-zinc-500 hover:text-indigo-400 transition"><IconUpload /></button>
                <button onClick={handleImportFromLink} title="Importar do Link" className="text-zinc-500 hover:text-indigo-400 transition"><IconLink /></button>
                <button onClick={handleNewProject} title="Novo Projeto" className="text-zinc-500 hover:text-indigo-400 transition"><IconPlus /></button>
            </div>
          </div>
          <div className="flex-1 p-2 space-y-1"><FileTree nodes={project.structure} onSelect={(id) => setActiveFileId(id)} activeId={activeFileId} onToggleFolder={handleToggleFolder} /></div>
        </aside>

        <section className="flex-1 flex flex-col bg-zinc-950 border-r border-zinc-800 relative min-w-0">
          <div className="flex-1 flex overflow-hidden">
            {(viewMode === 'code' || viewMode === 'split') && (
              <div className={`flex flex-col h-full bg-zinc-950 ${viewMode === 'split' ? 'w-1/2 border-r border-zinc-800' : 'w-full'}`}>
                <div className="h-10 bg-zinc-900 flex items-center justify-between px-4 text-sm border-b border-zinc-800 shrink-0">
                    <div className="flex items-center gap-2">{activeFile ? (<><IconFile /><span className="text-zinc-200">{activeFile.name}</span></>) : (<span className="text-zinc-500">Selecione um arquivo</span>)}</div>
                    <div className="flex items-center gap-2">
                        <button onClick={handleCopyAllCode} disabled={isCopying} title="Copiar Código Otimizado" className="flex items-center gap-2 text-xs px-2 py-1 bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 rounded-md disabled:opacity-50 disabled:cursor-not-allowed transition text-indigo-400">
                            {isCopying ? <div className="w-3 h-3 border-2 border-zinc-500 border-t-indigo-400 rounded-full animate-spin"/> : <IconClipboard size={14}/>}
                            {isCopying ? "Otimizando..." : "Copiar Projeto"}
                        </button>
                        <button onClick={handleSimulateAndFix} disabled={!activeFile || isFixingCode} title="Simular & Corrigir Erro" className="flex items-center gap-2 text-xs px-2 py-1 bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 rounded-md disabled:opacity-50 disabled:cursor-not-allowed transition text-amber-400">
                            {isFixingCode ? <div className="w-3 h-3 border-2 border-zinc-500 border-t-amber-400 rounded-full animate-spin"/> : <IconBug size={14}/>}
                            {isFixingCode ? "Analisando..." : "Simular & Corrigir"}
                        </button>
                    </div>
                </div>
                <div className="flex-1 overflow-auto bg-[#0d0d0d] p-4 code-font">{activeFile ? (<textarea className="w-full h-full bg-transparent border-none outline-none resize-none text-zinc-300 leading-relaxed text-sm" value={activeFile.content} spellCheck={false} onChange={(e) => setProject(prev => ({...prev, structure: updateFileContent(prev.structure, activeFile.id, e.target.value)}))} />) : (<div className="h-full flex flex-col items-center justify-center text-zinc-600 gap-4 text-center p-8"><IconTerminal /><p>Aguardando seleção de arquivo.</p></div>)}</div>
              </div>
            )}
            {(viewMode === 'preview' || viewMode === 'split') && (
              <div className={`flex flex-col h-full bg-zinc-900 ${viewMode === 'split' ? 'w-1/2' : 'w-full'}`}>
                <div className="flex-1 bg-[#18181b] overflow-hidden"><LivePreview project={project} /></div>
              </div>
            )}
          </div>
        </section>

        <aside className="w-[350px] bg-zinc-950 flex flex-col shrink-0">
          <div className="p-4 border-b border-zinc-800 flex items-center justify-between"><div className="flex items-center gap-2"><IconBot /><span className="font-semibold text-zinc-100">Assistente</span></div></div>
          <div className="flex-1 overflow-y-auto p-4 space-y-4">{messages.map((msg) => (<div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[90%] p-3 rounded-2xl text-xs leading-relaxed ${msg.role === 'user' ? 'bg-indigo-600 text-white' : msg.role === 'system' ? 'bg-amber-500/10 text-amber-400' : 'bg-zinc-800 text-zinc-200'}`}>{msg.text}</div></div>))}{isGenerating && (<div className="flex justify-start"><div className="bg-zinc-800 p-3 rounded-2xl"><div className="flex gap-1"><div className="w-1 h-1 bg-zinc-500 rounded-full animate-bounce" /><div className="w-1 h-1 bg-zinc-500 rounded-full animate-bounce delay-75" /><div className="w-1 h-1 bg-zinc-500 rounded-full animate-bounce delay-150" /></div></div></div>)}{!messages.length && !isGenerating && <div className="text-center text-sm text-zinc-500 pt-10">O que vamos construir hoje?</div>}<div ref={chatEndRef} /></div>
          <div className="p-4 border-t border-zinc-800 bg-zinc-950/50"><div className="relative"><textarea rows={1} value={userInput} onChange={(e) => setUserInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && (e.preventDefault(), handleSendMessage())} placeholder="Descreva seu app..." className="w-full bg-zinc-900 border border-zinc-800 rounded-xl px-4 py-3 pr-10 text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500 transition resize-none" /><button onClick={handleSendMessage} disabled={!userInput.trim() || isGenerating} className="absolute right-2 top-1/2 -translate-y-1/2 p-1.5 text-indigo-500 hover:text-indigo-400 transition disabled:opacity-50"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg></button></div></div>
        </aside>
      </main>

      {showExportModal && <div className="fixed inset-0 bg-black/70 backdrop-blur-md z-50 flex items-center justify-center p-4"><div className="bg-zinc-900 border border-zinc-800 w-full max-w-4xl rounded-3xl shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-200 flex flex-col max-h-[90vh]"><div className="p-6 border-b border-zinc-800 flex justify-between items-center bg-zinc-950/50 shrink-0"><h3 className="text-lg font-bold text-zinc-100 flex items-center gap-2"><IconShare /> Compilar & Exportar Universal</h3><button onClick={() => { setShowExportModal(false); setSelectedFormat(''); }} className="text-zinc-500 hover:text-white text-xl">&times;</button></div><div className="flex-1 overflow-y-auto p-6 space-y-8 scroll-smooth">{EXPORT_CATEGORIES.map((category) => (<div key={category.name} className="space-y-4"><h4 className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-400 border-l-2 border-indigo-500 pl-3">{category.name}</h4><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{category.options.map((option) => (<button key={option} onClick={() => setSelectedFormat(option)} className={`p-4 rounded-2xl border text-left transition relative overflow-hidden group ${selectedFormat === option ? 'border-indigo-500 bg-indigo-500/10 ring-1 ring-indigo-500' : 'border-zinc-800 bg-zinc-950 hover:bg-zinc-800'}`}><div className="relative z-10 text-zinc-100 font-semibold text-xs mb-1 truncate">{option}</div><div className="relative z-10 text-[10px] text-zinc-500 uppercase tracking-tighter">Pronto p/ Build</div>{selectedFormat === option && <div className="absolute top-0 right-0 p-1 bg-indigo-500 text-white rounded-bl-lg"><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="4"><polyline points="20 6 9 17 4 12"/></svg></div>}</button>))}</div></div>))}</div><div className="p-6 bg-zinc-950/80 border-t border-zinc-800 flex flex-col sm:flex-row justify-between items-center gap-4 shrink-0"><div className="text-[10px] text-zinc-500 font-medium">{selectedFormat ? (<span className="text-indigo-400 flex items-center gap-2"><IconTerminal /> Formato selecionado: <strong className="text-white">{selectedFormat}</strong></span>) : "Selecione o formato de saída desejado"}</div><div className="flex gap-3 w-full sm:w-auto"><button onClick={() => { setShowExportModal(false); setSelectedFormat(''); }} className="flex-1 sm:flex-none px-4 py-2 text-sm text-zinc-400 hover:text-white transition">Cancelar</button><button disabled={!selectedFormat || isExporting} onClick={handleExportProject} className="flex-1 sm:flex-none px-8 py-2 bg-indigo-600 text-white rounded-xl text-sm font-bold hover:bg-indigo-700 transition shadow-lg shadow-indigo-500/20 disabled:opacity-30 disabled:grayscale">{isExporting ? 'Compactando...' : 'Compilar App'}</button></div></div></div></div>}
      {showAIConfigModal && <AIConfigModal project={project} setProject={setProject} onClose={() => setShowAIConfigModal(false)} />}
    </div>
  );
};

const FileTree: React.FC<{nodes: FileNode[], onSelect: (id: string) => void, activeId: string | null, onToggleFolder: (id: string) => void, level?: number}> = ({ nodes, onSelect, activeId, onToggleFolder, level = 0 }) => (
  <>{nodes.map(node => (<div key={node.id}><div onClick={() => { if (node.type === 'file') { onSelect(node.id); } else { onToggleFolder(node.id); } }} className={`flex items-center gap-2 px-2 py-1.5 rounded-lg cursor-pointer transition text-xs ${activeId === node.id ? 'bg-indigo-500/10 text-indigo-400' : 'hover:bg-zinc-900 text-zinc-500 hover:text-zinc-200'}`} style={{ paddingLeft: `${(level * 12) + 8}px` }}>{node.type === 'folder' ? <IconFolder /> : <IconFile />}<span className="truncate">{node.name}</span></div>{node.type === 'folder' && node.isOpen && node.children && <FileTree nodes={node.children} onSelect={onSelect} activeId={activeId} onToggleFolder={onToggleFolder} level={level + 1} />}</div>))}</>
);

export default App;
